import { CHAT_FAILURE, CHAT_REQUEST, CHAT_SUCCESS, FETCH_MESSAGES_FAILURE, FETCH_MESSAGES_REQUEST, FETCH_MESSAGES_SUCCESS, SEND_MESSAGE_FAILURE, SEND_MESSAGE_REQUEST, SEND_MESSAGE_SUCCESS } from "../actionTypes";
import { createAction } from "./utils";

export const fetchChat = createAction({
  REQUEST: CHAT_REQUEST,
  SUCCESS: CHAT_SUCCESS,
  FAILURE: CHAT_FAILURE,
});

export const sendMessage = createAction({
  REQUEST: SEND_MESSAGE_REQUEST,
  SUCCESS: SEND_MESSAGE_SUCCESS,
  FAILURE: SEND_MESSAGE_FAILURE,
});

export const fetchMessage = createAction({
  REQUEST: FETCH_MESSAGES_REQUEST,
  SUCCESS: FETCH_MESSAGES_SUCCESS,
  FAILURE: FETCH_MESSAGES_FAILURE,
});
